### ISSUE TITLE
Issue of Duplicate Java

### ISSUE THREAD

**Issue by MakarkinPRO** [muhaym/Fabric.Sdk.Xamarin#1]
Have this issue:

Duplicate Java type found! Mappings between managed types and Java types must be unique. First Type: ‘IO.Fabric.Sdk.Android.Services.Events.IEventsStorageListenerImplementor, Fabric, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null’; Second Type: ‘Bindings.FabricSdk.Services.Events.IEventsStorageListenerImplementor, FabricSdk.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null’ Fabric Demo

**Comment by muhaym** [comment]
Can you help me reproducing this error?

**Comment by MakarkinPRO** [comment]
I solve it now. Thx8:20, 29 июля 2016 г., Abdul Muhaymin Arif notifications@github.com:Can you help me reproducing this error?  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.     -- Отправлено из мобильного приложения Яндекс.Почты

**Comment by muhaym** [comment]
Great. I am closing this thread :+1:
